const textArr=[
    'Cotton candy lollipop chocolate bar bonbon sweet roll chocolate cake. Wafer liquorice pastry cake cake caramels carrot cake danish cotton candy. Lemon drops marzipan lollipop carrot cake jelly-o. Lemon drops sweet roll lollipop muffin sugar plum. Icing liquorice chocolate cake toffee tart liquorice. Jujubes cake brownie dragée powder. Gingerbread macaroon soufflé candy canes shortbread danish. Gingerbread sweet marzipan tootsie roll sugar plum. Tart jujubes tart pudding caramels cake ice cream chupa chups. Marzipan marzipan pastry sweet roll chupa chups muffin fruitcake wafer. Jelly beans cookie cupcake sugar plum bonbon danish cotton candy jelly beans. Bear claw candy canes marzipan sesame snaps chocolate macaroon. Croissant icing sweet dessert apple pie. Jelly jelly-o jelly-o soufflé soufflé dragée.',
    'Chocolate gummi bears macaroon chocolate cupcake. Jelly danish cheesecake marzipan sweet roll. Apple pie sweet roll halvah sugar plum tiramisu lollipop. Carrot cake sesame snaps jelly-o cookie jelly-o topping dragée gingerbread. Jujubes wafer fruitcake sweet roll pudding cheesecake donut sugar plum. Donut donut chocolate cake topping cake sweet tart. Toffee cookie cupcake cotton candy ice cream gingerbread. Bear claw liquorice tiramisu chocolate bar caramels. Powder powder jelly sugar plum cotton candy. Gummies danish sweet brownie cotton candy tootsie roll halvah powder. Pudding sesame snaps fruitcake pie muffin oat cake. Gummies caramels sesame snaps sesame snaps shortbread chocolate bar gummi bears powder apple pie. Liquorice tart ice cream chocolate chocolate bar cupcake toffee.',
    'Caramels chupa chups brownie candy canes powder jelly beans tiramisu. Muffin chocolate sweet pastry shortbread fruitcake marzipan. Cotton candy powder gummies tootsie roll cookie pastry. Sweet pastry tart fruitcake lemon drops pudding powder. Bear claw chupa chups sesame snaps chupa chups gummi bears. Dessert dessert danish lemon drops powder lemon drops sugar plum tiramisu. Jelly beans donut carrot cake cake jelly gummi bears wafer jujubes sugar plum. Jelly beans tiramisu tiramisu dessert wafer. Soufflé cupcake candy canes croissant gummies donut bear claw cotton candy gingerbread. Apple pie jujubes icing chocolate cake cake. Sesame snaps sweet tart fruitcake gummies ice cream chupa chups. Brownie chocolate candy canes pie wafer. Tiramisu pudding jujubes chocolate cake chocolate cake biscuit gingerbread topping toffee. Lemon drops muffin cake gingerbread soufflé cotton candy chocolate sweet roll.',
    'Cookie cupcake danish brownie donut tootsie roll bear claw jelly beans icing. Chocolate bar marzipan lollipop cake halvah. Biscuit marshmallow chocolate cake jujubes bear claw. Toffee powder cake carrot cake jelly-o marzipan chupa chups cake donut. Candy jujubes cookie dragée cotton candy marshmallow. Cake cookie liquorice cake dragée soufflé. Candy wafer cheesecake macaroon icing carrot cake caramels fruitcake bear claw. Bear claw bear claw soufflé chocolate bar chocolate halvah oat cake. Jelly jelly caramels carrot cake toffee danish halvah sugar plum. Brownie pudding icing wafer brownie tiramisu fruitcake candy canes bonbon. Biscuit powder lemon drops tart topping bonbon. Lollipop soufflé liquorice shortbread marshmallow dessert oat cake chupa chups. Sesame snaps liquorice tiramisu cookie shortbread sweet roll. Shortbread caramels cotton candy ice cream biscuit.',
    'Bear claw chocolate cake biscuit danish topping toffee oat cake icing. Chocolate lemon drops oat cake biscuit danish tiramisu chocolate jelly beans macaroon. Carrot cake candy jujubes croissant donut danish caramels cookie wafer. Oat cake brownie muffin carrot cake pudding halvah tiramisu. Dessert chocolate cake pudding chocolate gummi bears jujubes jujubes bear claw. Dragée lemon drops gummi bears tart chupa chups cookie bonbon chocolate cake. Gingerbread topping bear claw pastry oat cake jelly beans jelly-o sugar plum. Ice cream topping jujubes cake candy. Candy canes jujubes jelly beans tart dragée. Pastry chocolate bar chupa chups donut sugar plum danish carrot cake sweet roll. Bear claw dragée chupa chups dessert marzipan cake marzipan cookie. Lollipop candy canes sesame snaps candy sweet toffee tiramisu danish gummies. Cake bonbon candy canes chupa chups soufflé. Halvah oat cake gummies soufflé dessert cake icing powder jelly.',
    'Carrot cake sesame snaps liquorice bear claw sweet roll lemon drops halvah cake tootsie roll. Wafer icing ice cream jelly-o sugar plum. Apple pie chocolate cake biscuit bonbon cake soufflé halvah cupcake gummi bears. Candy canes danish tiramisu lemon drops chupa chups candy pudding. Oat cake apple pie chocolate cake cake donut jelly-o cupcake halvah. Tiramisu donut jujubes cotton candy lollipop. Cake lemon drops brownie topping chupa chups. Lemon drops marzipan cotton candy marzipan dragée lollipop. Muffin apple pie gummi bears gummi bears icing cheesecake chocolate cake cupcake. Lollipop pudding chocolate bar cookie bonbon candy lemon drops bear claw. Biscuit fruitcake lollipop shortbread icing marzipan biscuit cake sweet roll. Biscuit powder gingerbread cake gummi bears.',
    'Cotton candy wafer chocolate cake cake macaroon caramels shortbread. Gingerbread brownie cookie liquorice gummies dessert marshmallow donut sweet roll. Bear claw apple pie gummies pudding pastry marzipan cookie sugar plum. Cake ice cream biscuit lemon drops soufflé. Cake croissant lemon drops bear claw fruitcake. Marshmallow tart cookie sweet dessert cotton candy. Cake chocolate cake halvah ice cream sugar plum gummies lemon drops halvah liquorice. Tart lemon drops gummies danish marzipan jelly sesame snaps marzipan shortbread. Gingerbread cheesecake sweet sesame snaps cotton candy marzipan sweet. Pie cotton candy oat cake ice cream carrot cake tootsie roll icing gummi bears. Sesame snaps muffin jelly-o gummies dragée pie lollipop sugar plum. Candy canes cheesecake tart tiramisu icing icing cookie jelly. Jelly beans chocolate cake pudding jelly jelly beans marzipan. Sugar plum candy tootsie roll jelly-o danish lollipop jelly-o cheesecake marshmallow.',
    'Jelly beans chocolate bar marshmallow carrot cake sugar plum bonbon pie. Oat cake donut dessert sweet roll cotton candy jujubes. Chocolate bar tart tiramisu croissant candy soufflé pudding. Bonbon chocolate tart candy sweet. Cake wafer dessert chupa chups pastry. Fruitcake chocolate cake candy shortbread carrot cake tootsie roll shortbread sugar plum bonbon. Cake dessert toffee soufflé chupa chups. Carrot cake chocolate cake carrot cake sweet powder. Halvah sweet roll jujubes bear claw bonbon chocolate gingerbread. Powder marzipan icing topping pudding. Sugar plum bear claw powder cake caramels topping. Cake toffee candy canes pie chocolate bar sweet roll sugar plum dragée.',
    'Toffee donut bonbon fruitcake biscuit tootsie roll chocolate bar fruitcake sweet roll. Lollipop jelly beans marshmallow gummies bonbon tiramisu cake. Muffin candy canes bonbon halvah marzipan. Jujubes chocolate caramels cheesecake marzipan. Pastry sesame snaps sweet sweet tart bear claw jujubes chocolate bar. Macaroon croissant tootsie roll marzipan lemon drops icing ice cream lollipop. Ice cream gummi bears cotton candy sweet topping topping croissant liquorice chocolate bar. Sesame snaps jelly-o topping muffin macaroon marshmallow sweet marzipan chocolate. Caramels topping pudding bear claw biscuit soufflé. Liquorice powder liquorice gummi bears fruitcake sesame snaps pie. Gingerbread dessert tiramisu candy canes bonbon sweet ice cream sweet roll carrot cake. Pie oat cake dragée cake jelly wafer marzipan. Fruitcake tiramisu pie muffin apple pie.',
];

const formId=document.querySelector('#formId');
const textAmount=document.querySelector('#textAmount');
const Text=document.querySelector('#Text');

formId.addEventListener('submit',function(e){
    e.preventDefault();

    const inpVal=parseInt(textAmount.value);
    const randomVal=Math.floor(Math.random() * textArr.length);

    if(isNaN(inpVal) || inpVal <= 0 || inpVal >9){
        Text.innerHTML=`<p>${textArr[randomVal]}</p>`;
    }else{
        const slicedArr=textArr.slice(0,inpVal);
        const finalArr = slicedArr.map(function(singleArr){
            return `<p>${singleArr}</p>`
        }).join('');

        Text.innerHTML=finalArr;
    }

})